#!usr/bin/python3

#my_dna = 'GATGGGATTGGGGTTTTCCCCTCCCATGTGCTCAAGACTGGCGCTAAAAGTTTTGAGCTTCTCAAAAGTCTAGAGCCACCGTCCAGGGAGCAGGTAGCTGCTGGGCTCCGGGGACACTTTGCGTTCGGGCTGGGAGCGTGCTTTCCACGACGGTGACACGCTTCCCTGGATTGGCAGCCAGACTGCCTTCCGGGTCACTGCCATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCTGTCCCCCTTGCCGTCCCAAGCAATGGATGATTTGATGCTGTCCCCGGACGATATTGAACAATGGTTCACTGAAGACCCAGGTCCAGATGAAGCTCCCAGAATTCGCCAGAGGCTGCTCCCCCCGTGGCCCCTGCACCAGCAGCTCCTACACCGGCGGCCCCTGCACCAGCCCCCTCCTGGCCCCTGTCATCTTCTGTCCCTTCCCAGAAAACCTACCAGGGCAGCTACGGTTTCCGTCTGGGCTTCTTGCATTCTGGGACAGCCAAGTCTGTGACTTGCACGTACTCCCCTGCCCTCAACAAGATGTTTTGCCAACTGGCCAAGACCTGCCCTGTGCAGCTGTGGGTTGATTCCACACCCCCGCCCGGCACCCGCGTCCGCGCCATGGCCATCTACAAGCAGTCACAGCACATGACGGAGGTTGTGAGGCGCTGCCCCCACCATGAGCGCTGCTCAGATAGCGATGGTCTGGCCCCTCCTCAGCATCTTATCCGAGTGGAAGGAAATTTGCGTGTGGAGTATTTGGATGACAGAAACACTTTTCG'

#my_dna_sub = 'GATGCGCTTC'

## lenght
#len(my_dna)
#len(my_dna_sub) #10

## -1-2-  AT and GC content
##sub
#AT_ct_sub = 100/len(my_dna_sub)*(my_dna_sub.count("A") + my_dna_sub.count("T"))
#GC_ct_sub = 100/len(my_dna_sub)*(my_dna_sub.count("G") + my_dna_sub.count("C")) 

## full
#ATcontent = 100/len(my_dna)*(my_dna.count("A") + my_dna.count("T"))
#GCcontent = 100/len(my_dna)*(my_dna.count("G") + my_dna.count("C"))

## -3- find reverse complement:
## input data

## Ori_seq5-3 = 'ATGCAGGGGAAACATGATTCAGGAC'  
## Com_seq3-5 = 'TACGTCCCCTTTGTACTAAGTCCTG'  
## RevCom_seq5-3 = 'GTCCTGAATCATGTTTCCCCTGCAT'

my_dna = 'A'

if my_dna == 'A':
    message = 'T'
    print(message)
elif my_dna == 'T':
    message = 'A'
    print(message)
elif my_dna == 'G':
    message = 'C'
    print(message)
elif my_dna == 'C':
    message = 'G'
    print(message)
else:
    message = "this is an undefined char. "
    print(message)


